import { listKnowledgeNotes, readKnowledgeNote, writeKnowledgeNote } from "../knowledge/fs";
import { searchRelevantNotes } from "../knowledge/search";
import { renderMarkdownNote } from "../knowledge/markdown";
import { runResearchAgent } from "./research-agent";
import { runSummarizerAgent } from "./summarizer-agent";
import { runLinkingAgent } from "./linking-agent";
import { runWriterAgent } from "./writer-agent";
import { runValidatorAgent } from "./validator-agent";
import type { RunResult, WorkflowStep, FileChange, KnowledgeNote } from "../types";
import type { WriterOutput, LinkingOutput } from "../ai/schemas";

function initWorkflowSteps(): WorkflowStep[] {
  return [
    { id: "scan", label: "Scanning knowledge base", status: "pending" },
    { id: "research", label: "Research Agent", status: "pending" },
    { id: "summarizer", label: "Summarizer Agent", status: "pending" },
    { id: "linking", label: "Linking Agent", status: "pending" },
    { id: "writer", label: "Writer Agent", status: "pending" },
    { id: "validator", label: "Validator Agent", status: "pending" },
    { id: "persist", label: "Persisting notes", status: "pending" },
  ];
}

function markRunning(workflow: WorkflowStep[], id: string): number {
  const step = workflow.find((s) => s.id === id);
  if (step) {
    step.status = "running";
  }
  return Date.now();
}

function markComplete(
  workflow: WorkflowStep[],
  id: string,
  details: string,
  startTime: number
): void {
  const step = workflow.find((s) => s.id === id);
  if (step) {
    step.status = "completed";
    step.details = details;
    step.durationMs = Date.now() - startTime;
  }
}

function markFailed(
  workflow: WorkflowStep[],
  id: string,
  details: string,
  startTime: number
): void {
  const step = workflow.find((s) => s.id === id);
  if (step) {
    step.status = "failed";
    step.details = details;
    step.durationMs = Date.now() - startTime;
  }
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function uniqueStrings(arr: string[]): string[] {
  return [...new Set(arr.map((s) => s.trim()).filter(Boolean))];
}

async function persistGeneratedNotes(
  writerNotes: WriterOutput["notes"],
  linkingOps: LinkingOutput["operations"],
  existingNotes: KnowledgeNote[]
): Promise<FileChange[]> {
  const fileChanges: FileChange[] = [];
  const processedSlugs = new Set<string>();

  for (const noteDraft of writerNotes.slice(0, 3)) {
    const slug = slugify(noteDraft.slug);
    if (processedSlugs.has(slug)) continue;
    processedSlugs.add(slug);

    // Find matching linking operation
    const linkingOp = linkingOps.find(
      (op) => slugify(op.slug) === slug
    );
    const action = linkingOp?.action || "create";

    // Find existing note if updating
    const existingNote = existingNotes.find((n) => n.slug === slug);

    let mergedDraft: {
      slug: string;
      title: string;
      summary: string;
      keyPoints: string[];
      related: string[];
      bodySections: { heading: string; bullets: string[] }[];
    };

    if (existingNote && action === "update") {
      // Merge with existing note
      mergedDraft = {
        slug,
        title: existingNote.title || noteDraft.title,
        summary: noteDraft.summary || existingNote.summary,
        keyPoints: uniqueStrings([
          ...existingNote.keyPoints,
          ...noteDraft.keyPoints,
        ]).slice(0, 8),
        related: uniqueStrings([
          ...existingNote.related,
          ...noteDraft.related,
          ...(linkingOp?.related || []),
        ])
          .map(slugify)
          .filter((r) => r !== slug)
          .slice(0, 8),
        bodySections: noteDraft.bodySections || [],
      };
    } else {
      // Create new note
      mergedDraft = {
        slug,
        title: noteDraft.title,
        summary: noteDraft.summary,
        keyPoints: uniqueStrings(noteDraft.keyPoints).slice(0, 8),
        related: uniqueStrings([
          ...noteDraft.related,
          ...(linkingOp?.related || []),
        ])
          .map(slugify)
          .filter((r) => r !== slug)
          .slice(0, 8),
        bodySections: noteDraft.bodySections || [],
      };
    }

    // Render markdown from structured data
    const markdown = renderMarkdownNote(mergedDraft);

    // Write to disk
    const writtenPath = await writeKnowledgeNote(slug, markdown);

    fileChanges.push({
      slug,
      title: mergedDraft.title,
      action: existingNote ? "update" : "create",
      path: `knowledge/${slug}.md`,
      reason: linkingOp?.reason || noteDraft.updateReason || "Generated by agent workflow",
      related: mergedDraft.related,
      markdown,
    });
  }

  return fileChanges;
}

export async function runMasterWorkflow(query: string): Promise<RunResult> {
  const workflow = initWorkflowSteps();

  // Step 1: Scan knowledge base
  let startTime = markRunning(workflow, "scan");
  const { notes, storageMode } = await listKnowledgeNotes();
  const selectedNotes = searchRelevantNotes(query, notes, 4);
  markComplete(
    workflow,
    "scan",
    `${selectedNotes.length} relevant notes from ${notes.length} total`,
    startTime
  );

  // Step 2: Research Agent
  startTime = markRunning(workflow, "research");
  let research;
  try {
    research = await runResearchAgent({
      query,
      selectedNotes,
      allNoteTitles: notes.map((n) => n.title),
    });
    markComplete(
      workflow,
      "research",
      `${research.relevantFindings.length} findings, confidence: ${research.confidence}`,
      startTime
    );
  } catch (error) {
    markFailed(workflow, "research", String(error), startTime);
    throw new Error(`Research agent failed: ${error}`);
  }

  // Step 3: Summarizer Agent
  startTime = markRunning(workflow, "summarizer");
  let summary;
  try {
    summary = await runSummarizerAgent({ query, research });
    markComplete(
      workflow,
      "summarizer",
      `${summary.keyPoints.length} key points`,
      startTime
    );
  } catch (error) {
    markFailed(workflow, "summarizer", String(error), startTime);
    throw new Error(`Summarizer agent failed: ${error}`);
  }

  // Step 4: Linking Agent
  startTime = markRunning(workflow, "linking");
  let linking;
  try {
    linking = await runLinkingAgent({
      query,
      research,
      summary,
      existingSlugs: notes.map((n) => n.slug),
    });
    markComplete(
      workflow,
      "linking",
      `${linking.operations.length} note operations planned`,
      startTime
    );
  } catch (error) {
    markFailed(workflow, "linking", String(error), startTime);
    throw new Error(`Linking agent failed: ${error}`);
  }

  // Step 5: Writer Agent
  startTime = markRunning(workflow, "writer");
  let writer;
  try {
    writer = await runWriterAgent({
      query,
      research,
      summary,
      linking,
      selectedNotes,
    });
    markComplete(
      workflow,
      "writer",
      `${writer.notes.length} note drafts created`,
      startTime
    );
  } catch (error) {
    markFailed(workflow, "writer", String(error), startTime);
    throw new Error(`Writer agent failed: ${error}`);
  }

  // Step 6: Validator Agent
  startTime = markRunning(workflow, "validator");
  let validator;
  try {
    validator = await runValidatorAgent({
      writer,
      linking,
      existingSlugs: notes.map((n) => n.slug),
    });
    markComplete(
      workflow,
      "validator",
      validator.approved ? "Approved" : `Approved with ${validator.issues.length} issues`,
      startTime
    );
  } catch (error) {
    markFailed(workflow, "validator", String(error), startTime);
    throw new Error(`Validator agent failed: ${error}`);
  }

  // Step 7: Persist notes
  startTime = markRunning(workflow, "persist");
  let fileChanges: FileChange[] = [];
  try {
    if (validator.safeToWrite) {
      fileChanges = await persistGeneratedNotes(
        writer.notes,
        linking.operations,
        notes
      );
    }
    markComplete(
      workflow,
      "persist",
      `${fileChanges.length} files written`,
      startTime
    );
  } catch (error) {
    markFailed(workflow, "persist", String(error), startTime);
    // Don't throw here - we still want to return the answer
  }

  return {
    query,
    answer: writer.answer,
    workflow,
    selectedNotes,
    fileChanges,
    storageMode,
  };
}
